// Auto-generated by LibreLane
module A37_A(
`ifdef USE_POWER_PINS
  inout VSS,
  inout VDD,
`endif
  input i_clk,
  output i_clk_PU,
  output i_clk_PD,
  input i_rst_n,
  output i_rst_n_PU,
  output i_rst_n_PD,
  input i_uart_rx,
  output i_uart_rx_PU,
  output i_uart_rx_PD,
  output o_uart_tx_CS,
  output o_uart_tx_SL,
  output o_uart_tx_IE,
  output o_uart_tx_OE,
  output o_uart_tx_PU,
  output o_uart_tx_PD,
  output o_uart_tx_OUT,
  output o_uart_tx_PDRV0,
  output o_uart_tx_PDRV1,
  input o_uart_tx_IN
);
endmodule
